# Generated by Django 2.0.6 on 2018-06-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
    ]
