# Generated by Django 2.0.6 on 2018-06-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20180615_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='team_away',
            field=models.ForeignKey(blank=True, db_column='team_away', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_away', to='football.Teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='team_home',
            field=models.ForeignKey(blank=True, db_column='team_home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_home', to='football.Teams'),
        ),
        migrations.AlterModelTable(
            name='games',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teams',
            table=None,
        ),
    ]
