# Generated by Django 2.0.6 on 2018-06-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20180615_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'managed': False},
        ),
    ]
