# Generated by Django 2.0.6 on 2018-06-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20180615_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='games',
            table='games',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='teams',
        ),
    ]
