# Generated by Django 2.0.5 on 2018-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='release_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='release_stop',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Awaiting approval'), (3, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
