# Generated by Django 2.0.5 on 2018-06-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercises.Person')),
            ],
        ),
    ]
